require(["baja!", "dialogs", "jquery"], (baja, dialogs, $) => {
  "use strict";

  const sub = new baja.Subscriber();

  // ok dialogs with function (called when dialog is about to show)
  dialogs
    .showOk((dlg, jq) => {
      // dlg: dialog instance
      // jq: jQuery wrapper around the dialog's content DOM element

      // inner text of dialog's DOM element is updated using jQuery's text method. Which prevents XSS attacks.
      jq.text("Loading...");

      // update dialog content
      const update = (ramp) => {
        // the ramp's getOutDisplay method is auto-generated by BajaScript based upon the frozen slots a ramp has.
        jq.text(ramp.getOutDisplay());
      }

      // Called whenever the Ramp changes.
      sub.attach("changed", function (prop) {
        if (prop.getName() === "out") {
          update(this);
        }
      });

      // ORD is used to resolve and subscribe the Ramp component on the station
      // by create a proxy version of the Ramp component in the browser proxy version has all slots the java based version that running on the station also receive events for any changed property values.
      baja.Ord.make("station:|slot:/BajaScriptExamples/Components/Ramp")
        .get({ subscriber: sub })
        .then(update);
    })
    .promise()
    .finally(function () {
      // Called when the dialog is closed.
      sub.unsubscribeAll();
      sub.detach();
    });
});
